# Site settings
title: "Kumaran"
email: kumaran.masilamani@yahoo.co.uk
description: "Full stack polyglot agile developer with Kotlin, GoLang, Scala, Java with frontend skills"
baseurl: ""
url: "http://kumaran.me/"
title_description: "Full stack polyglot agile developer with Kotlin, GoLang, Scala, Java with frontend skills and a Certified Scrum Master "
title_image: "https://media.licdn.com/dms/image/C4D03AQHUrqeVUGEtjg/profile-displayphoto-shrink_200_200/0?e=1560384000&v=beta&t=7fzpnb83b53hxpJOnohWzFcPs4nUcXOa3WRACnrgpVA"
google_analytics: ""
disqus_account: kumaran
github_repository: https://github.com/m-kumaran/m-kumaran.github.io
addthis_id: ra-513c6fa83da6ec6
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
instagram_username:
reddit_username:
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
