# Site settings
title: "Kumaran"
email: kumaran.masilamani@yahoo.co.uk
description: "Full stack polyglot agile developer with experience in Golang, Scala and Java."
baseurl: ""
url: "http://kumaran.me/"
title_description: "An enthusiastic, versatile, full stack polyglot developer with programming experience in Scala, Golang, Java in AWS and GCP"
title_description2: "Certified Scrum Master and an evangelist of Agile methodologies"
#title_image: "https://media.licdn.com/dms/image/C4D03AQHUrqeVUGEtjg/profile-displayphoto-shrink_200_200/0?e=1560384000&v=beta&t=7fzpnb83b53hxpJOnohWzFcPs4nUcXOa3WRACnrgpVA"
#title_image: "https://media.licdn.com/dms/image/C4D03AQHUrqeVUGEtjg/profile-displayphoto-shrink_100_100/0?e=1567641600&v=beta&t=2WWo5KirfHNsyDMRSFl0wEwjYbPbWnux2gnu8v7hCQc"
title_image: "/img/face.jpg"

google_analytics: ""
disqus_account:
github_repository: https://github.com/m-kumaran/m-kumaran.github.io
addthis_id: ra-99999999
post_limit: 10

# Social usernames/URLs
twitter_username: kumaran_rajesh
github_username:  m-kumaran
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/kumaran-masilamani-98b13b7/
google_plus_link:
stackoverflow_link: https://stackexchange.com/users/466251/kumaran
xing_link:
facebook_link: https://www.facebook.com/kumaran.masilamani


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
